import new1 from '../assets/images/new1.png';
import new2 from '../assets/images/new2.png';
import new3 from '../assets/images/new3.png';
import new4 from '../assets/images/new4.png';
import top1 from '../assets/images/top1.png';
import top2 from '../assets/images/top2.png';
import top3 from '../assets/images/top3.png';
import top4 from '../assets/images/top4.png';
import cate1 from '../assets/images/cate1.png';
import cate2 from '../assets/images/cate2.png';
import cate3 from '../assets/images/cate3.png';
import cate4 from '../assets/images/cate4.png';
import { img102 } from '../assets/icons';
interface Review {
  id: number;
  name: string;
  comment: string;
  rate: number;
}
export const newClothes = [
  { id: 1, name: 'Classic White T-Shirt', stars: 4.5, price: 25.99, discount: 10, img: new1 },
  { id: 2, name: 'Denim Jacket', stars: 4.8, price: 59.99, discount: 15, img: new2 },
  { id: 3, name: 'Casual Hoodie', stars: 4.6, price: 45.5, discount: 20, img: new3 },
  { id: 4, name: 'Slim Fit Jeans', stars: 4.7, price: 65.0, discount: 5, img: new4 },
  { id: 5, name: 'Leather Jacket', stars: 5, price: 120.99, discount: 10, img: top1 },
  { id: 6, name: 'Striped Polo Shirt', stars: 4.7, price: 35.5, discount: 5, img: top2 },
  { id: 7, name: 'Cargo Pants', stars: 4.6, price: 50.0, discount: 15, img: top3 },
  { id: 8, name: 'Wool Sweater', stars: 4.8, price: 70.0, discount: 20, img: top4 },
];
export const topSelling = [
  { id: 1, name: 'Leather Jacket', stars: 5, price: 120.99, discount: 10, img: top1 },
  { id: 2, name: 'Striped Polo Shirt', stars: 4.7, price: 35.5, discount: 5, img: top2 },
  { id: 3, name: 'Cargo Pants', stars: 4.6, price: 50.0, discount: 15, img: top3 },
  { id: 4, name: 'Wool Sweater', stars: 4.8, price: 70.0, discount: 20, img: top4 },
  { id: 5, name: 'Classic White T-Shirt', stars: 4.5, price: 25.99, discount: 10, img: new1 },
  { id: 6, name: 'Denim Jacket', stars: 4.8, price: 59.99, discount: 15, img: new2 },
  { id: 7, name: 'Casual Hoodie', stars: 4.6, price: 45.5, discount: 20, img: new3 },
  { id: 8, name: 'Slim Fit Jeans', stars: 4.7, price: 65.0, discount: 5, img: new4 },
];
export const cate = [
  { id: 1, name: 'Formal', img: cate1 },
  { id: 2, name: 'Casual', img: cate2 },
  { id: 3, name: 'Sports', img: cate3 },
  { id: 4, name: 'Modest', img: cate4 },
];
export const reviews: Review[] = [
  {
    id: 1,
    name: 'Ahmad Khalil',
    comment: 'Great quality and fast delivery! Totally recommend it .',
    rate: 4.5,
  },
  { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
  {
    id: 3,
    name: 'Mohammed Tamimi',
    comment: 'Average experience, item came slightly delayed.',
    rate: 3,
  },
  {
    id: 4,
    name: 'Lina Hasan',
    comment: 'Excellent customer support and quality product!',
    rate: 5,
  },
  { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
  { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
  { id: 7, name: 'Omar Saeed', comment: 'Good for the price, but not the best quality.', rate: 3 },
  {
    id: 8,
    name: 'Fatima Saleh',
    comment: 'Item arrived earlier than expected, great service!',
    rate: 4,
  },
  { id: 9, name: 'Hadi Nasser', comment: 'Did not meet my expectations, disappointed.', rate: 2 },
  { id: 10, name: 'Nour Khalaf', comment: 'Perfect in every way! Highly recommend.', rate: 5 },
];
export const products = [
  {
    id: 1,
    title: 'Luxury Gold Ring',
    category: 'Accessories',
    gender: 'Women',
    style: 'Formal',
    sizes: ['S', 'M'],
    colors: ['#D4AF37', '#F5F5DC'],
    price: 200,
    sale: false,
    isNew: true,
    rating: 4.5,
    images: [img102],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr:
      'An elegant luxury gold ring designed for formal occasions, crafted with precision and premium materials.',
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
    details: {
      material: '18K Gold Plated Alloy',
      pattern: 'Classic Polished Finish',
      colors: 'Gold, Champagne',
      size: 'Adjustable ring size (S–M)',
      finish: 'High-gloss polished surface',
      care: 'Avoid water, perfumes, and chemicals. Store in a dry place.',
    },
  },

  {
    id: 2,
    title: 'Navy Blue Hijab',
    category: 'Scarves',
    gender: 'Men',
    style: 'Casual',
    sizes: ['S', 'M', 'L'],
    colors: ['#0A1E3F'],
    price: 250,
    sale: true,
    isNew: false,
    rating: 4.7,
    images: [new2],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr:
      'A lightweight navy blue hijab designed for daily comfort with a smooth satin feel.',
    details: {
      material: '100% Satin Silk',
      pattern: 'Plain',
      colors: 'Navy Blue',
      size: '90 x 90 cm (approx.)',
      finish: 'Soft stitched edges',
      care: 'Hand wash cold or dry clean recommended.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 3,
    title: 'Printed Formal Hijab',
    category: 'Scarves',
    gender: 'Men',
    style: 'Formal',
    sizes: ['M', 'L'],
    colors: ['#3A3A3A', '#BFA980'],
    price: 280,
    sale: true,
    isNew: false,
    rating: 4.6,
    images: [new3],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A sophisticated formal hijab featuring an elegant Persian-inspired print.',
    details: {
      material: '100% Satin Silk',
      pattern: 'Persian Paisley Print',
      colors: 'Navy, Burgundy, Gold, Light Blue accents',
      size: '90 x 90 cm (approx.)',
      finish: 'Hand-rolled edges',
      care: 'Dry clean recommended.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 4,
    title: 'Blazer Brooch Pin',
    category: 'Accessories',
    gender: 'Kids',
    style: 'Formal',
    sizes: ['One Size'],
    colors: ['#C9A227'],
    price: 150,
    sale: true,
    isNew: false,
    rating: 4.2,
    images: [new4],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A stylish blazer brooch pin designed to add elegance to formal outfits.',
    details: {
      material: 'Metal Alloy',
      pattern: 'Minimalist Decorative',
      colors: 'Gold',
      size: 'One Size',
      finish: 'Matte gold coating',
      care: 'Wipe gently with a dry cloth.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 5,
    title: 'White Casual Hijab',
    category: 'Scarves',
    gender: 'Women',
    style: 'Casual',
    sizes: ['S', 'M'],
    colors: ['#FFFFFF'],
    price: 220,
    sale: false,
    isNew: false,
    rating: 4.4,
    images: [new1],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A breathable white casual hijab perfect for everyday wear.',
    details: {
      material: 'Chiffon Blend',
      pattern: 'Plain',
      colors: 'White',
      size: '90 x 90 cm (approx.)',
      finish: 'Soft hemmed edges',
      care: 'Hand wash recommended.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 6,
    title: 'Beige Knit Sweater',
    category: 'T-shirts',
    gender: 'Women',
    style: 'Casual',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#E8DCCA'],
    price: 300,
    sale: true,
    isNew: false,
    rating: 4.5,
    images: [new2],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A cozy beige knit sweater designed for comfort and warmth.',
    details: {
      material: 'Cotton & Wool Blend',
      pattern: 'Knitted Texture',
      colors: 'Beige',
      size: 'S – XL',
      finish: 'Ribbed cuffs and hem',
      care: 'Machine wash cold, lay flat to dry.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 7,
    title: 'Gold Necklace',
    category: 'Accessories',
    gender: 'Women',
    style: 'Formal',
    sizes: ['One Size'],
    colors: ['#D4AF37'],
    price: 200,
    sale: false,
    isNew: false,
    rating: 4.8,
    images: [new3],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A refined gold necklace suitable for formal occasions.',
    details: {
      material: 'Gold Plated Stainless Steel',
      pattern: 'Minimal Chain',
      colors: 'Gold',
      size: '45 cm length',
      finish: 'High polish',
      care: 'Avoid moisture and chemicals.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 8,
    title: 'Elegant Gold Earrings',
    category: 'Accessories',
    gender: 'Women',
    style: 'Formal',
    sizes: ['One Size'],
    colors: ['#FFD700'],
    price: 350,
    sale: true,
    isNew: false,
    rating: 4.9,
    images: [new4],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'Elegant gold earrings crafted for luxurious formal looks.',
    details: {
      material: 'Gold Plated Alloy',
      pattern: 'Drop Earrings',
      colors: 'Gold',
      size: 'Medium length',
      finish: 'Glossy finish',
      care: 'Store separately to avoid scratches.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 9,
    title: 'Luxury Watch',
    category: 'Accessories',
    gender: 'Women',
    style: 'Formal',
    sizes: ['One Size'],
    colors: ['#000000', '#C0C0C0'],
    price: 500,
    sale: true,
    isNew: false,
    rating: 4.7,
    images: [new2],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A luxury watch combining precision engineering with elegant design.',
    details: {
      material: 'Stainless Steel & Sapphire Glass',
      pattern: 'Minimal Dial',
      colors: 'Black, Silver',
      size: 'Adjustable strap',
      finish: 'Brushed steel',
      care: 'Clean with soft cloth, avoid water immersion.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },

  {
    id: 10,
    title: 'Blue Pattern Hijab',
    category: 'Scarves',
    gender: 'Women',
    style: 'Casual',
    sizes: ['M', 'L'],
    colors: ['#1E3A8A'],
    price: 270,
    sale: false,
    isNew: true,
    rating: 4.6,
    images: [new3],
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    wholeDescr: 'A stylish patterned hijab with elegant blue accents.',
    details: {
      material: '100% Satin Silk',
      pattern: 'Persian Paisley Print',
      colors: 'Navy, Burgundy, Gold, Light Blue accents',
      size: '90 x 90 cm (approx.)',
      finish: 'Hand-rolled edges',
      care: 'Dry clean recommended.',
    },
    reviews: [
      {
        id: 1,
        name: 'Ahmad Khalil',
        comment: 'Great quality and fast delivery! Totally recommend it.',
        rate: 4.5,
      },
      { id: 2, name: 'Sara Ali', comment: 'Good overall but packaging could be better.', rate: 4 },
      {
        id: 3,
        name: 'Mohammed Ahmad',
        comment: 'Average experience, item came slightly delayed.',
        rate: 3,
      },
      {
        id: 4,
        name: 'Lina Hasan',
        comment: 'Excellent customer support and quality product!',
        rate: 5,
      },
      { id: 5, name: 'Yousef Odeh', comment: 'Not what I expected, color was a bit off.', rate: 2 },
      { id: 6, name: 'Rana Qasem', comment: 'Loved it! Will definitely order again.', rate: 5 },
      {
        id: 7,
        name: 'Omar Saeed',
        comment: 'Good for the price, but not the best quality.',
        rate: 3,
      },
      {
        id: 8,
        name: 'Fatima Saleh',
        comment: 'Item arrived earlier than expected, great service!',
        rate: 4,
      },
      {
        id: 9,
        name: 'Hadi Nasser',
        comment: 'Did not meet my expectations, disappointed.',
        rate: 2,
      },
    ],
  },
];
