export const reviews = [
  {
    id: 1,
    username: 'Sarah',
    rating: 4.5,
    title: 'Amazing Product!',
    date: '2 days ago',
    text: "I'm blown away by the quality and style of the shirt! Exceeded my expectations. The fabric feels luxurious and it’s incredibly comfortable to wear. I’ve already received so many compliments!",
  },
  {
    id: 2,
    username: 'James',
    rating: 5,
    title: 'Highly Recommend',
    date: '5 days ago',
    text: 'Absolutely love this! The material feels premium and it fits perfectly. Shipping was fast and the packaging was excellent. I would definitely purchase again and recommend it to friends.',
  },
  {
    id: 3,
    username: 'Emily',
    rating: 4,
    title: 'Very Nice',
    date: '1 week ago',
    text: 'The product is good, though the color is slightly different than expected. Overall, I’m happy with the purchase. It’s well made, comfortable, and looks great when worn. Would consider buying other colors too.',
  },
  {
    id: 4,
    username: 'Michael',
    rating: 4.8,
    title: 'Exceeded My Expectations',
    date: '3 weeks ago',
    text: 'The quality of this item is outstanding. Every detail is well-thought-out, from the stitching to the finish. It’s stylish, comfortable, and durable. I am extremely satisfied with this purchase and will buy more.',
  },
  {
    id: 5,
    username: 'Olivia',
    rating: 4.2,
    title: 'Good Value for Money',
    date: '1 month ago',
    text: 'I wasn’t sure what to expect, but this product turned out to be better than I thought. It’s comfortable, stylish, and feels premium. The only minor issue was slight difference in color, but overall very happy.',
  },
  {
    id: 6,
    username: 'Daniel',
    rating: 5,
    title: 'Perfect Fit and Quality',
    date: '1 month ago',
    text: 'This is honestly one of the best purchases I’ve made this year. The sizing is accurate, the texture is soft, and it feels very high-end. After several washes, the fabric still looks brand new. I’ll be ordering another one soon.',
  },
  {
    id: 7,
    username: 'Lina',
    rating: 4.3,
    title: 'Stylish and Comfortable',
    date: '6 weeks ago',
    text: 'Very stylish piece. I love how it feels on my skin and how easy it is to match with different outfits. Took one star off because delivery took a bit longer than expected.',
  },
  {
    id: 8,
    username: 'Ahmad',
    rating: 4.9,
    title: 'Top Tier Quality',
    date: '2 months ago',
    text: 'The attention to detail is impressive. From the stitching to the texture of the fabric, everything feels premium. I’ve worn it several times already and it still looks brand new. Worth every dollar.',
  },
  {
    id: 9,
    username: 'Sophia',
    rating: 4.6,
    title: 'Beautiful Design',
    date: '2 months ago',
    text: 'The design is absolutely gorgeous and unique. I love how it stands out without being too flashy. Very comfortable for long hours of wear as well.',
  },
  {
    id: 10,
    username: 'Yousef',
    rating: 4,
    title: 'Nice but Slightly Large',
    date: '2 months ago',
    text: 'Overall a really good product. The quality is there, but I felt the size runs slightly larger than expected. Other than that, it’s comfortable and stylish.',
  },
  {
    id: 11,
    username: 'Maya',
    rating: 5,
    title: 'Absolutely Love It',
    date: '3 months ago',
    text: 'I’m obsessed with this product! The comfort level is amazing and the fabric feels incredibly soft on the skin. I’ve already recommended it to my family and friends. Definitely a must-buy.',
  },
  {
    id: 12,
    username: 'Omar',
    rating: 4.7,
    title: 'Great for Everyday Wear',
    date: '3 months ago',
    text: 'Perfect for everyday use. It’s lightweight, breathable, and very comfortable. I wear it for work and casual outings and it always looks good.',
  },
  {
    id: 13,
    username: 'Nour',
    rating: 3.9,
    title: 'Good but Could Improve',
    date: '4 months ago',
    text: 'The product is decent overall. The fabric is nice and it feels comfortable, but I expected the color to be slightly more vibrant. Still a good purchase for the price.',
  },
  {
    id: 14,
    username: 'Hassan',
    rating: 4.8,
    title: 'Premium Feel',
    date: '4 months ago',
    text: 'From the moment I opened the package, I could tell it was high quality. The packaging, the material, and the finish all feel premium. It’s rare to find such quality at this price point.',
  },
  {
    id: 15,
    username: 'Rana',
    rating: 4.4,
    title: 'Very Satisfied',
    date: '5 months ago',
    text: 'Overall, I am very satisfied with this product. It’s comfortable, stylish, and easy to maintain. I’ve received several compliments every time I wear it. Will definitely buy again.',
  },
];
