import img1 from '../assets/images/1.jpg';
import img3 from '../assets/images/3.png';
import casual from '../assets/images/img2.png';
import formal from '../assets/images/img3.png';
export const newClothes = [
  {
    id: 1,
    name: 'T-shirt with tape Details',
    stars: 5,
    price: 22,
    discount: 4,
    img: img1,
  },
  {
    id: 2,

    name: 'SKINNY FIT JEANS',
    stars: 4.5,
    price: 11,
    discount: 6,
    img: img3,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 5, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 6, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 7, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 8, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 9, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 10, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 11, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 12, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 13, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },

  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },

  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  { id: 4, name: 'SLEEVE STRIPED T-SHIRT', stars: 1.7, price: 33, discount: 6, img: img3 },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  { id: 14, name: 'T-shirt', stars: 1.3, price: 33, discount: 9, img: img3 },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
  {
    id: 3,

    name: 'CHECKERED SHIRT',
    stars: 3,
    price: 12,
    discount: 0,
    img: img1,
  },
];
export const cate = [
  { id: 1, title: 'Casual', img: casual },
  { id: 2, title: 'Formal', img: formal },
  { id: 3, title: 'Islamic', img: formal },
  { id: 4, title: 'Gym', img: casual },
];
export const clotherCate = [
  { id: 1, title: 'T-shirts' },
  { id: 2, title: 'Shorts' },
  { id: 3, title: 'Shirts' },
  { id: 4, title: 'Hoodie' },
  { id: 5, title: 'Jeans' },
];
export const colors = [
  '#00C12B',
  '#F50606',
  '#F5DD06',
  '#F57906',
  '#06CAF5',
  '#063AF5',
  '#7D06F5',
  '#F506A4',
  '#FFFFFF',
  '#000000',
];
export const size = [
  { id: 1, title: 'XX-Small' },
  { id: 2, title: 'X-Small' },
  { id: 3, title: 'Small' },
  { id: 5, title: 'medium' },

  { id: 6, title: 'Large' },
  { id: 7, title: 'X-Large' },
  { id: 8, title: 'XX-Large' },
  { id: 9, title: '3X-Large' },
  { id: 10, title: '4X-Large' },
];
