import img1 from '../assets/images/1.jpg';
import img3 from '../assets/images/3.png';
import casual from '../assets/images/img2.png';
import formal from '../assets/images/img3.png';
export const newClothes = [
  {
    id: 1,
    name: 'T-shirt with tape Details',
    stars: 5,
    price: 222,
    discount: 4,
    img: img1,
  },
  {
    id: 2,
    name: 'Sleeve striped t-shirt',
    stars: 2,
    price: 11,
    discount: 50,
    img: img3,
  },
  {
    id: 3,
    name: 'skinny fit jeans',
    stars: 4,
    price: 123,
    discount: 98,
    img: img1,
  },
  {
    id: 5,
    name: 'skinny fit jeans',
    stars: 3.5,
    price: 411,
    discount: 77,
    img: img3,
  },
  {
    id: 6,
    name: 'skinny fit jeans',
    stars: 2.5,
    price: 999,
    discount: 40,
    img: img3,
  },
  {
    id: 7,
    name: 'skinny fit jeans',
    stars: 1.5,
    price: 76,
    discount: 2,
    img: casual,
  },
  {
    id: 8,
    name: 'skinny fit jeans',
    stars: 2,
    price: 422,
    discount: 12,
    img: img3,
  },
  {
    id: 9,
    name: 'skinny fit jeans',
    stars: 1.5,
    price: 66,
    discount: 11,
    img: img3,
  },
  {
    id: 10,
    name: 'skinny fit jeans',
    stars: 4.5,
    price: 55,
    discount: 22,
    img: casual,
  },
  {
    id: 12,
    name: 'skiy fit jeans',
    stars: 2,
    price: 99,
    discount: 1,
    img: casual,
  },
  {
    id: 13,
    name: 'skinny jeans',
    stars: 3.5,
    price: 33,
    discount: 12,
    img: img3,
  },
  {
    id: 14,
    name: 'skinny fit ans',
    stars: 3.5,
    price: 66,
    discount: 44,
    img: img3,
  },
  {
    id: 15,
    name: 'skinny fit js',
    stars: 3.5,
    price: 126,
    discount: 10,
    img: img3,
  },
  {
    id: 16,
    name: 'skinny f jeans',
    stars: 6,
    price: 887,
    discount: 66,
    img: img3,
  },
  {
    id: 17,
    name: 'skinny fit jeans',
    stars: 3,
    price: 88,
    discount: 33,
    img: formal,
  },
  {
    id: 18,
    name: 'skinny fit ',
    stars: 1,
    price: 88,
    discount: 33,
    img: img3,
  },
  {
    id: 19,
    name: 'skinny jeans',
    stars: 3.5,
    price: 88,
    discount: 33,
    img: formal,
  },
  {
    id: 20,
    name: ' jeans',
    stars: 4.5,
    price: 88,
    discount: 33,
    img: formal,
  },
];
export const cate = [
  { id: 1, title: 'Casual', img: casual },
  { id: 2, title: 'Formal', img: formal },
  { id: 3, title: 'Islamic', img: formal },
  { id: 4, title: 'Gym', img: casual },
];
export const clotherCate = [
  {
    id: 1,
    title: 'Womens',
    data: {
      Casual: ['T-shirts', 'Jeans', 'Hoodies'],
      Formal: ['Dresses', 'Scarves', 'Blazers'],
      Sport: ['Tracksuits', 'T-shirts'],
    },
  },
  {
    id: 2,
    title: 'Mens',
    data: {
      Casual: ['T-shirts', 'Shirts', 'Jeans'],
      Formal: ['Suits', 'Shirts'],
      Sport: ['Tracksuits', 'Shorts'],
    },
  },
  {
    id: 3,
    title: 'Kids',
    data: {
      Girls: ['Dresses', 'T-shirts'],
      Boys: ['T-shirts', 'Shorts'],
      Babies: ['Sets', 'Bodysuits'],
    },
  },
];

export const colors = [
  '#00C12B',
  '#F50606',
  '#F5DD06',
  '#F57906',
  '#06CAF5',
  '#063AF5',
  '#7D06F5',
  '#F506A4',
  '#FFFFFF',
  '#000000',
];
export const size = [
  { id: 1, title: 'XX-Small' },
  { id: 2, title: 'X-Small' },
  { id: 3, title: 'Small' },
  { id: 5, title: 'medium' },

  { id: 6, title: 'Large' },
  { id: 7, title: 'X-Large' },
  { id: 8, title: 'XX-Large' },
  { id: 9, title: '3X-Large' },
  { id: 10, title: '4X-Large' },
];
